### ISSUE TITLE
Top menu does not appear on android in vertical mode

### ISSUE THREAD

**Issue by Popolechien** [openzim/openedx#153]
So if I open phzh_core-english-one_en_2020-09.zim on my phone (huawei android 9) the menu at the top does not appear and I'm stuck on a rather boring landing page
![core](https://user-images.githubusercontent.com/21675885/93892716-1f40a380-fced-11ea-8ad3-422910e29b0b.jpg)

If I tilt the phone horizontally and the image resize _then_ I can see the menu (if I tilt back it disappears again)

![corde](https://user-images.githubusercontent.com/21675885/93892856-47c89d80-fced-11ea-9c7c-ddd7b2f24098.jpg)

**Comment by rgaudin** [comment]
This apparently due to the size of the viewport. I can replicate that with a small device factor on a regular browser.

```css
// assets/main.css @(max-width: 640px)
.zim-course-index, .zim-courseware {
	display: none;
}
```
